### ISSUE TITLE
VOTs2023

### ISSUE THREAD

**Issue by 2006pmach** [votchallenge/integration#8]
Hi 

I am trying to integrate the new version of the toolkit into our codebase. I updated trax, pulled the newest version of the toolkit and used the new vot.py file I found in this repo since the old ones were not working anymore. Now when running the vot2020 stack I get the following error

```
@@TRAX:hello "trax.name=" "trax.family=" "trax.image=path;" "trax.region=rectangle;" "trax.description=" "trax.version=4" "vot=python" "trax.channels=color;" 
@@TRAX:initialize "549.0000,249.0000,23.0000,57.0000" 
@@TRAX:frame "file:///scratch_net/clariden/chmayer/vot/vot2022-stb/sequences/agility/color/00000001.jpg" 
@@TRAX:state "549.0000,249.0000,23.0000,57.0000" 
@@TRAX:frame "file:///scratch_net/clariden/chmayer/vot/vot2022-stb/sequences/agility/color/00000002.jpg" 
/scratch_net/clariden/chmayer/conda_envs/pytracking-transformer/lib/python3.7/site-packages/torch/nn/functional.py:3063: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Using /scratch_net/clariden/chmayer/tmp as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /scratch_net/clariden/chmayer/tmp/_prroi_pooling/build.ninja...
Building extension module _prroi_pooling...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module _prroi_pooling...
/scratch_net/clariden/chmayer/conda_envs/pytracking-transformer/lib/python3.7/site-packages/torch/nn/functional.py:3063: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/chmayer/github/pytracking-transformer/pytracking/run_vot.py", line 14, in run_vot2020
    tracker.run_vot2020(debug, visdom_info)
  File "/home/chmayer/github/pytracking-transformer/pytracking/evaluation/tracker.py", line 595, in run_vot2020
    handle.report(pred, conf)
  File "/home/chmayer/github/pytracking-transformer/pytracking/evaluation/vots2023.py", line 128, in report
    self._trax.status(status, properties)
  File "/scratch_net/clariden/chmayer/conda_envs/pytracking-transformer/lib/python3.7/site-packages/trax/server.py", line 123, in status
    assert(isinstance(objects, list))
AssertionError
@@TRAX:quit 
Process exited with code (1)
```

Something seems misaligned here. The new vot.py file produces the status and the properties dict but trax is expecting a list for some reason. 

The inputs to `self._trax.status()` are 
```
status Rectangle 554.280517578125,240.6689910888672 24.481735229492188x47.17734146118164
properties {'confidence': 1.0}
```
Any ideas what is going wrong?

**Comment by lukacu** [comment]
This confidence seems strange, can you publish the overall wrapper code?

**Comment by lukacu** [comment]
From the log it seems that you are trying to run single-object tracker. There was an issue with the vot.py for single-object trackers that is now fixed. Simply download the new vot.py from this repository.

**Comment by 2006pmach** [comment]
I think there is still a problems with the vot.py file [here](https://github.com/votchallenge/integration/blob/d46c9a8f7b22adcc8661a88f683b2ddbf3bc09cc/python/vot.py#LL124C9-L131C49).

From what I understand status is in any case a list of tuples. So at the bottom you try to access the first tuple in the status list via a string. That doesn't work. Do we need to add the confidence to the second element (the dict) in the tuple?
```
if not self._multiobject:
    status = [(convert(status), {})]
else:
    assert isinstance(status, (list, tuple))
    status = [(convert(x), {}) for x in status]

if not confidence is None and not self._multiobject:
    status[0]['confidence'] = confidence
``` 

So should it be `status[0][1]['confidence'] = confidence` instead?

**Comment by lukacu** [comment]
It should work without confidence, but yes, there is a problem with this notation. Unfortunately, I have discovered another problem that confidence is not passed on and I am resolving that first. I will let you know once that is solved, but for now it only works with no confidence score.

**Comment by 2006pmach** [comment]
Okay thx. I think there are more problems when running on SOT but for now I would like to move on to VOTS2023.
I setup the workspace and downloaded the sequences. When I run the tracker and call 
`handle = vot.VOT("mask", multiobject=True)` it produces the following output and is hanging
`@@TRAX:hello "trax.name=" "trax.family=" "trax.multiobject=1" "trax.image=path;" "trax.region=mask;" "trax.description=" "trax.version=4" "vot=python" "trax.channels=color;"` 
When I terminate the script with CTRL+C I get
```
Traceback (most recent call last):
  File "run_vot.py", line 43, in <module>
    main()
  File "run_vot.py", line 39, in main
    run_vots2023(args.tracker_name, args.tracker_param, args.run_id, args.debug, visdom_info)
  File "run_vot.py", line 13, in run_vots2023
    tracker.run_vots2023(debug, visdom_info)
  File "../pytracking/evaluation/tracker.py", line 555, in run_vots2023
    handle = vot.VOT('mask', multiobject=True)
  File "../pytracking/evaluation/vots2023.py", line 56, in __init__
    request = self._trax.wait()
  File "/scratch_net/clariden/chmayer/conda_envs/pytracking-transformer/lib/python3.7/site-packages/trax/server.py", line 89, in wait                                                         
    status = TraxStatus.decode(trax_server_wait(self._handle.reference, byref(timage), byref(tobjects), properties.reference))                                                                
KeyboardInterrupt
@@TRAX:quit
```
Any ideas why it is not working? It is not so easy to debug this stuff...

**Comment by lukacu** [comment]
Yes, debug is not easy if you look at it as a standalone program. I assume that you have run it from the command line? The hello message introduces the tracker to the toolkit, it waits for data from the toolkit to continue.

Btw, I have solved the problem with confidence, but you have to update trax to use it. I will release a new version soon, but for now it is on Github only.

**Comment by 2006pmach** [comment]
Hm yes it is a standalone similar to what is shown [here](https://www.votchallenge.net/howto/integration_multiobject.html)
I followed the template and initialized my tracker and then called `handle = vot.VOT("mask", multiobject=True)` but it never advances to the next line. Any idea why it is hanging here? Can I somehow get an error instead of an infinite waiting time? What is is waiting for here?

**Comment by 2006pmach** [comment]
I think I found the problem but I am unable to solve it. So I have the standalone similar to the example mentioned above. It uses the `vot.py` integration file to access trax etc. I noticed that I am nowhere specifying the path to the workspace. How do I pass the workspace path to trax or the integration `vot.py` file?

**Comment by lukacu** [comment]
You do not, the tracker has no concept of a workspace in trax, it only serves the requests of the toolkit which coordinates the experiment. This is why the toolkit has to run the tracker process.

**Comment by 2006pmach** [comment]
I think I got it running now. Thanks for your help!
